/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package propLlibreria.Interficie;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author Alice
 */
public class VistaOrdenat extends javax.swing.JPanel {

    /**
     * Creates new form VistaOrdenat
     */
    public VistaOrdenat() {
        initComponents();
        mostrarLlibresEstanteries();
    }
    
    private void mostrarLlibresEstanteries(){
        try {
            PropTableModel myData = new PropTableModel();
            ArrayList<String> columns = new ArrayList<String>();
            ArrayList<ArrayList<String> > est = new ArrayList<ArrayList<String> >();
            ArrayList<ArrayList<String> > rows = new ArrayList<ArrayList<String> >();            
            columns.add("Estanteria");
            columns.add("ISBN");
            columns.add("Títol");
            columns.add("Autor");
            columns.add("Any");
            est = CtrlInterficie.seleccionaAllEstanteries();
            for (int i=0; i<est.size();i++){
                ArrayList<String> estanteria=est.get(i);
                try{
                    ArrayList<ArrayList<String> > llibres = new ArrayList<ArrayList<String> >();
                    llibres = CtrlInterficie.consultarLlibresEstanteria(Integer.parseInt(estanteria.get(0)), Integer.parseInt(estanteria.get(1)));
                    for (int j=0; j<llibres.size(); j++){
                         ArrayList<String> row = new ArrayList<String>();
                         row.add(estanteria.get(0)+","+estanteria.get(1));
                         row.add(llibres.get(j).get(0));
                         row.add(llibres.get(j).get(1));
                         row.add(llibres.get(j).get(2));
                         row.add(llibres.get(j).get(4));

                         rows.add(row);                     
                    } 
                }catch (Exception e){
                    System.out.println("Excepció!");
                }
            }            
                    
            myData.setRowsValues(rows);
            myData.setColumnsValues(columns);
            JTable taula = new JTable((TableModel) myData);
            TaulaOrdenada.setViewportView(taula);
        }
        catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TaulaOrdenada = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bSortir = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TaulaOrdenada.setViewportView(jTable1);

        bSortir.setText("Tancar");
        bSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSortirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaulaOrdenada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bSortir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TaulaOrdenada, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bSortir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSortirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSortirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TaulaOrdenada;
    private javax.swing.JButton bSortir;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
