/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package propLlibreria.Interficie;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author towerthousand
 */
public class VistaGestioEliminar extends javax.swing.JPanel {

    private String tipusObjecte;
    
    /**
     * Creates new form VistaGestioEliminar
     */
    public VistaGestioEliminar() {
        initComponents();
    }
    
    public void redisplay(String newTipusObjecte) {
        tipusObjecte = newTipusObjecte;
        refillTable();
    }

    private void refillTable() {
        PropTableModel myData = new PropTableModel();
        ArrayList<String> columns = new ArrayList<String>();
        ArrayList<ArrayList<String> > rows = new ArrayList<ArrayList<String> >();
        
        switch(tipusObjecte) {
            case "Àrea": {
                columns.add("Nom Àrea");
                //TODO: Agafar les arees de veritat
                ArrayList<String> obj = new ArrayList<String>();
                obj.add("TestArea");
                rows.add(obj);
                rows.add(obj);
                break;
            }
            case "Secció": {
                columns.add("Nom Secció");
                columns.add("Nom Àrea Pare");
                //TODO: Agafar les seccions de veritat
                ArrayList<String> obj = new ArrayList<String>();
                obj.add("TestSeccio");
                obj.add("TestAreaPare");
                rows.add(obj);
                rows.add(obj);
                break;
            }
            case "Temàtica": {
                columns.add("Nom Temàtica");
                columns.add("Nom Secció Pare");
                //TODO: Agafar les tematiques de veritat
                ArrayList<String> obj = new ArrayList<String>();
                obj.add("TestTematica");
                obj.add("TestSeccióPare");
                rows.add(obj);
                rows.add(obj);
                break;
            }
            case "Estanteria": {
                columns.add("PosicióX");
                columns.add("PosicióY");
                columns.add("Estants");
                columns.add("Llargada");
                //TODO: Agafar les estanteries de veritat
                ArrayList<String> obj = new ArrayList<String>();
                obj.add("TestPosicioX");
                obj.add("TestPosicioY");
                obj.add("TestEstants");
                obj.add("TestLlargada");
                rows.add(obj);
                rows.add(obj);
                break;
            }
            case "Llibre": {
                columns.add("ISBN");
                columns.add("Títol");
                columns.add("Autor");
                columns.add("Editorial");
                columns.add("Any");
                columns.add("Edició");
                columns.add("Temàtica Principal");
                //TODO: Agafar les seccions de veritat
                ArrayList<String> obj = new ArrayList<String>();
                obj.add("TestISBN");
                obj.add("TestTitol");
                obj.add("TestAutor");
                obj.add("TestEditorial");
                obj.add("TestAny");
                obj.add("TestEdicio");
                obj.add("TestTematicaPrincipal");
                rows.add(obj);
                rows.add(obj);
                break;
            }
        }
        
        myData.setColumnsValues(columns);
        myData.setRowsValues(rows);
        jTable1.setModel(myData);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(476, 405));
        setMinimumSize(new java.awt.Dimension(476, 405));
        setPreferredSize(new java.awt.Dimension(476, 405));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog (null, "Seguro que quieres borrar este elemento?","Warning",dialogButton);
        if(result != JOptionPane.YES_OPTION) return;
        //TODO ELIMINAR EL PUTU OBJECTE
        refillTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
