/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package propLlibreria.Interficie;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author towerthousand
 */
public class VistaGestioModificarEstanteria extends javax.swing.JPanel {

    /**
     * Creates new form VistaGestióAfegirEstanteria
     */
    public VistaGestioModificarEstanteria() {
        initComponents();
    }

    public void resetFields() {
        ArrayList<ArrayList<String> > estanteries = CtrlInterficie.seleccionaAllEstanteries();
        boolean b = !estanteries.isEmpty();
        comboEstanteria.setEnabled(b);
        spinEstants.setEnabled(b);
        spinY.setEnabled(b);
        spinX.setEnabled(b);
        spinLlargada.setEnabled(b);
        botoModificar.setEnabled(b);
        String[] model = new String[estanteries.size()];
        for(int i = 0; i < estanteries.size(); ++i)
            model[i] = "X:" + estanteries.get(i).get(0) + ", Y:" + estanteries.get(i).get(1);
        comboEstanteria.setModel(new javax.swing.DefaultComboBoxModel(model));
        if(!b) return;
        refill();
    }
    
    private void refill() {
        ArrayList<ArrayList<String> > estanteries = CtrlInterficie.seleccionaAllEstanteries();
        int s = comboEstanteria.getSelectedIndex();
        spinX.setValue(Integer.parseInt(estanteries.get(s).get(0)));
        spinY.setValue(Integer.parseInt(estanteries.get(s).get(1)));
        spinEstants.setValue(Integer.parseInt(estanteries.get(s).get(2)));
        spinLlargada.setValue(Integer.parseInt(estanteries.get(s).get(3)));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoModificar = new javax.swing.JToggleButton();
        labelPosicioX = new javax.swing.JLabel();
        spinX = new javax.swing.JSpinner();
        labelPosicioY = new javax.swing.JLabel();
        spinY = new javax.swing.JSpinner();
        labelLlargada = new javax.swing.JLabel();
        spinLlargada = new javax.swing.JSpinner();
        spinEstants = new javax.swing.JSpinner();
        labelEstants = new javax.swing.JLabel();
        comboEstanteria = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(212, 220, 245));
        setMaximumSize(new java.awt.Dimension(476, 405));
        setMinimumSize(new java.awt.Dimension(476, 405));
        setPreferredSize(new java.awt.Dimension(476, 405));

        botoModificar.setText("Modificar");
        botoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoModificarActionPerformed(evt);
            }
        });

        labelPosicioX.setText("Posicio X");

        spinX.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        labelPosicioY.setText("Posicio Y");

        spinY.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        labelLlargada.setText("Llargada");

        spinLlargada.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        spinEstants.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        labelEstants.setText("Estants");

        comboEstanteria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEstanteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstanteriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botoModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelPosicioX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPosicioY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelLlargada, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEstants, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spinX, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(spinEstants, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(spinLlargada, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(spinY, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(comboEstanteria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(comboEstanteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPosicioX)
                    .addComponent(spinX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPosicioY)
                    .addComponent(spinY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstants)
                    .addComponent(spinEstants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLlargada)
                    .addComponent(spinLlargada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botoModificar)
                .addContainerGap(138, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoModificarActionPerformed
        int x = (Integer) spinX.getValue();
        int y = (Integer) spinY.getValue();
        int estants = (Integer) spinEstants.getValue();
        int llargada = (Integer) spinLlargada.getValue();
        try {
           ArrayList<ArrayList<String> > estanteries = CtrlInterficie.seleccionaAllEstanteries();
           int s = comboEstanteria.getSelectedIndex();
           int xo = Integer.parseInt(estanteries.get(s).get(0));
           int yo = Integer.parseInt(estanteries.get(s).get(1));
           CtrlInterficie.modificarLlargadaEstanteria(xo, yo, llargada);
           CtrlInterficie.modificarNumFilesEstanteria(xo, yo, estants);
           if(xo != x || yo != y)CtrlInterficie.modificarCoordenadesEstanteria(xo, yo, x, y);
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error al modificar.\nCodi d'error: " + e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);  
            return;
        }
        JOptionPane.showMessageDialog(null, "Modificat correctament","Info",JOptionPane.INFORMATION_MESSAGE);
        resetFields();
    }//GEN-LAST:event_botoModificarActionPerformed

    private void comboEstanteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstanteriaActionPerformed
        refill();
    }//GEN-LAST:event_comboEstanteriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botoModificar;
    private javax.swing.JComboBox comboEstanteria;
    private javax.swing.JLabel labelEstants;
    private javax.swing.JLabel labelLlargada;
    private javax.swing.JLabel labelPosicioX;
    private javax.swing.JLabel labelPosicioY;
    private javax.swing.JSpinner spinEstants;
    private javax.swing.JSpinner spinLlargada;
    private javax.swing.JSpinner spinX;
    private javax.swing.JSpinner spinY;
    // End of variables declaration//GEN-END:variables
}
