package propLlibreria.Interficie;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.concurrent.CancellationException;
import java.util.concurrent.ExecutionException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;

public class VistaMentreOrdena extends javax.swing.JPanel {
    
    ArrayList<ArrayList<String>> est= new ArrayList<ArrayList<String>>();
    SwingWorker<Boolean, Void> ordena;

    public VistaMentreOrdena() {
        initComponents();
        bExport.setVisible(false);
        bExportTotal.setVisible(false);
    }
     
    public void ordenar(boolean tip, ArrayList<ArrayList<String>> e, ArrayList<ArrayList<String>> l){
        //tipus=1 = heuristico
        //tipus=0 = exacto
        bExport.setVisible(false);
        bExportTotal.setVisible(false);
        bSortir.setText("Cancel·lar");
        labProgressGif.setVisible(true);
        labKeepCalm.setText("Ordenant. Espera si us plau.");
        final boolean tipus=tip;
        est=e;
        final ArrayList<ArrayList<String>> lib=l;        
        ordena = new SwingWorker<Boolean, Void>() {
            @Override
            protected Boolean doInBackground() throws Exception {
                try{
                    CtrlInterficie.reordenacioBiblioteca(tipus, est, lib);
                }catch (Exception e){
                    System.out.println(e);
                    JFrame frame = new JFrame();
                    JOptionPane.showMessageDialog(frame,
                    "No hi ha prous llocs a les estanteries per la quantitat de llibres que hi ha.",
                    "Pocs llocs a les estanteries",
                    JOptionPane.WARNING_MESSAGE);
                    
                    tornarEnrerePerError();
                    ordena.cancel(true);
                    }
                return true;
            }
            
            @Override
            protected void done() {
                boolean status;
                try {
                    status = get();                    
                    if(status){
                        ordenacioAcabada();
                    } 
                } catch (InterruptedException e) {
                    // This is thrown if the thread's interrupted.
                } catch (ExecutionException e) {
                    // This is thrown if we throw an exception from doInBackground. 
                } catch (CancellationException e) {
                    // This is thrown if we throw an exception from doInBackground. 
                }
            }
        };
        
        ordena.execute();
    }
    
    private void ordenacioAcabada(){
        bExport.setVisible(true);
        bExportTotal.setVisible(true);
        bSortir.setText("Tornar al menú");
        labProgressGif.setVisible(false);
        labKeepCalm.setText("Ordenació acabada.");
    }
    
    private void tornarEnrerePerError(){
        VistaPrincipal v = (VistaPrincipal)SwingUtilities.getWindowAncestor(this);
        v.ferVisibleOrdenar();  
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labKeepCalm = new javax.swing.JLabel();
        bSortir = new javax.swing.JButton();
        bExport = new javax.swing.JButton();
        labProgressGif = new javax.swing.JLabel();
        bExportTotal = new javax.swing.JButton();

        setBackground(new java.awt.Color(212, 220, 245));
        setPreferredSize(new java.awt.Dimension(500, 500));

        labKeepCalm.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        labKeepCalm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labKeepCalm.setText("Ordenant. Espera si us plau.");
        labKeepCalm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bSortir.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        bSortir.setText("Cancel·lar");
        bSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSortirActionPerformed(evt);
            }
        });

        bExport.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        bExport.setText("Veure ordenació feta");
        bExport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExportActionPerformed(evt);
            }
        });

        labProgressGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/propLlibreria/Interficie/icons/spinner-blue.gif"))); // NOI18N

        bExportTotal.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        bExportTotal.setText("Veure ordenació total");
        bExportTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bExportTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExportTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bExportTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(labProgressGif))
                            .addComponent(bSortir, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(labKeepCalm)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(labKeepCalm)
                .addGap(50, 50, 50)
                .addComponent(labProgressGif)
                .addGap(59, 59, 59)
                .addComponent(bExport, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bExportTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(bSortir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSortirActionPerformed
        if(bSortir.getText().equals("Cancel·lar")){
            JFrame dialog = new JFrame();
            int n = JOptionPane.showConfirmDialog( dialog, "Estas segur que ho vols cancel·lar?\n", "Cancelar ordenació", JOptionPane.YES_NO_OPTION);
            if(n==0){
                ordena.cancel(true);
                VistaPrincipal v = (VistaPrincipal)SwingUtilities.getWindowAncestor(this);
                v.ferVisiblePrincipal();                
            }
        }else{
            VistaPrincipal v = (VistaPrincipal)SwingUtilities.getWindowAncestor(this);
            v.ferVisiblePrincipal();
        }       
    }//GEN-LAST:event_bSortirActionPerformed

    private void bExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExportActionPerformed
        VistaOrdenat llibresOrdenats = new VistaOrdenat(est);
        JFrame frameLlibresOrdenats = new JFrame();
        frameLlibresOrdenats.setIconImage(Toolkit.getDefaultToolkit().getImage("resources/bookIcon.png"));
        frameLlibresOrdenats.setSize(new Dimension(600,400));
        frameLlibresOrdenats.setResizable(false);
        frameLlibresOrdenats.setLocation(20, 20);
        frameLlibresOrdenats.add(llibresOrdenats);
        frameLlibresOrdenats.setVisible(true);
    }//GEN-LAST:event_bExportActionPerformed

    private void bExportTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExportTotalActionPerformed
        VistaOrdenat llibresOrdenats = new VistaOrdenat(null);
        JFrame frameLlibresOrdenats = new JFrame();
        frameLlibresOrdenats.setIconImage(Toolkit.getDefaultToolkit().getImage("resources/bookIcon.png"));
        frameLlibresOrdenats.setSize(new Dimension(600,400));
        frameLlibresOrdenats.setResizable(false);
        frameLlibresOrdenats.setLocation(20, 20);
        frameLlibresOrdenats.add(llibresOrdenats);
        frameLlibresOrdenats.setVisible(true);
    }//GEN-LAST:event_bExportTotalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExport;
    private javax.swing.JButton bExportTotal;
    private javax.swing.JButton bSortir;
    private javax.swing.JLabel labKeepCalm;
    private javax.swing.JLabel labProgressGif;
    // End of variables declaration//GEN-END:variables
}
