package propLlibreria.Interficie;
import javax.swing.SwingUtilities;


public class VistaOrdenacio extends javax.swing.JPanel {
  
    private int escollit=0;
    private final VistaMentreOrdena vMentreOrdena;
    
    public VistaOrdenacio() {
        initComponents();
        //if(ctrlInterficie.obtenirNumLlibres()>10) 
            labAvis.setVisible(true);
        //else labAvis.setVisible(false);
        vMentreOrdena = new VistaMentreOrdena();        
    }
    
    private void ocultarTot(){
        bBandB.setVisible(false);
        bCancelar.setVisible(false);
        bHeur.setVisible(false);
        labAvis.setVisible(false);
        labInfo.setVisible(false);
    }
    
    private void cridaVistaMentreOrdena() {
        ocultarTot();
        if(vMentreOrdena == null) return;
        vMentreOrdena.tipusOrdenacio(escollit);
        vMentreOrdena.setVisible(true);
        javax.swing.GroupLayout layeredLayout = new javax.swing.GroupLayout(layered);
        layered.setLayout(layeredLayout);
        layeredLayout.setHorizontalGroup(
            layeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vMentreOrdena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layeredLayout.setVerticalGroup(
            layeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vMentreOrdena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layered.setLayer(vMentreOrdena, javax.swing.JLayeredPane.DEFAULT_LAYER);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layered = new javax.swing.JLayeredPane();
        bCancelar = new javax.swing.JButton();
        bHeur = new javax.swing.JButton();
        bBandB = new javax.swing.JButton();
        labAvis = new javax.swing.JLabel();
        labInfo = new javax.swing.JLabel();

        bCancelar.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        bCancelar.setText("Cancel·lar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bHeur.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        bHeur.setText("Mètode heurístic");
        bHeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHeurActionPerformed(evt);
            }
        });

        bBandB.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        bBandB.setText("Mètode exacte");
        bBandB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBandBActionPerformed(evt);
            }
        });

        labAvis.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        labAvis.setForeground(new java.awt.Color(255, 51, 51));
        labAvis.setText("<html>Compte! La quantitat de llibres és <b>molt gran per utilitzar un mètode exacte</b>. El temps d'espera de reordenació pot superar els 5 minuts.</html>");
        labAvis.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        labInfo.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        labInfo.setText("Escull de quina forma vols ordenar:");

        javax.swing.GroupLayout layeredLayout = new javax.swing.GroupLayout(layered);
        layered.setLayout(layeredLayout);
        layeredLayout.setHorizontalGroup(
            layeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredLayout.createSequentialGroup()
                            .addComponent(labAvis, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(54, 54, 54))
                        .addGroup(layeredLayout.createSequentialGroup()
                            .addComponent(labInfo)
                            .addGap(44, 44, 44)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredLayout.createSequentialGroup()
                        .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(bBandB, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bHeur, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        layeredLayout.setVerticalGroup(
            layeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(labAvis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labInfo)
                .addGap(29, 29, 29)
                .addGroup(layeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bBandB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHeur, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layered.setLayer(bCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered.setLayer(bHeur, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered.setLayer(bBandB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered.setLayer(labAvis, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layered.setLayer(labInfo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bBandBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBandBActionPerformed
        escollit=0;
        cridaVistaMentreOrdena();
    }//GEN-LAST:event_bBandBActionPerformed

    private void bHeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHeurActionPerformed
        // TODO add your handling code here:
        escollit=1;
        cridaVistaMentreOrdena();
    }//GEN-LAST:event_bHeurActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        VistaPrincipal v = (VistaPrincipal)SwingUtilities.getWindowAncestor(this);
        v.ferVisibleGestionar();
    }//GEN-LAST:event_bCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBandB;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bHeur;
    private javax.swing.JLabel labAvis;
    private javax.swing.JLabel labInfo;
    private javax.swing.JLayeredPane layered;
    // End of variables declaration//GEN-END:variables
}
