/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package propLlibreria.Interficie;

/**
 *
 * @author Alice
 */
public class VistaOrdenacio extends javax.swing.JPanel {

    /**
     * Creates new form VistaOrdenacio
     */
    public VistaOrdenacio() {
        initComponents();
        //if(ctrlInterficie.obtenirNumLlibres()>10) 
            labAvis.setVisible(true);
        //else labAvis.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labInfo = new javax.swing.JLabel();
        labAvis = new javax.swing.JLabel();
        bBandB = new javax.swing.JButton();
        bHeur = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        labInfo.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        labInfo.setText("Escull de quina forma vols ordenar:");

        labAvis.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        labAvis.setForeground(new java.awt.Color(255, 51, 51));
        labAvis.setText("<html>Compte! La quantitat de llibres és <b>molt gran per utilitzar un mètode exacte</b>. El temps d'espera de reordenació pot superar els 5 minuts.</html>");
        labAvis.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        bBandB.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        bBandB.setText("Mètode exacte");
        bBandB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBandBActionPerformed(evt);
            }
        });

        bHeur.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        bHeur.setText("Mètode heurístic");
        bHeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHeurActionPerformed(evt);
            }
        });

        Cancelar.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        Cancelar.setText("Cancel·lar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(bBandB, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(bHeur, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labAvis, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labInfo)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labAvis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labInfo)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBandB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHeur, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bBandBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBandBActionPerformed
        // TODO add your handling code here:
        //CtrlInterficie.ordenarPerB&B();
    }//GEN-LAST:event_bBandBActionPerformed

    private void bHeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHeurActionPerformed
        // TODO add your handling code here:
        //CtrlInterficie.ordenarPerHeuristic();
    }//GEN-LAST:event_bHeurActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        //tancar finestra D:
    }//GEN-LAST:event_CancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton bBandB;
    private javax.swing.JButton bHeur;
    private javax.swing.JLabel labAvis;
    private javax.swing.JLabel labInfo;
    // End of variables declaration//GEN-END:variables
}
