package propLlibreria.Interficie;
import javax.swing.SwingUtilities;


public class VistaOrdenacio extends javax.swing.JPanel {
  
    private final VistaMentreOrdena vMentreOrdena;
    
    public VistaOrdenacio() {
        initComponents();
        if(CtrlInterficie.seleccionaAllLlibres().size() > 10)   labAvis.setVisible(true);
        else labAvis.setVisible(false);
        vMentreOrdena = new VistaMentreOrdena();        
    }
    
    private void ocultarTot(){
        panPregunta.setVisible(false);
    }
    
    private void cridaVistaMentreOrdena() {
        ocultarTot();
        if(vMentreOrdena == null) return;
        vMentreOrdena.setVisible(true);
        javax.swing.GroupLayout layeredLayout = new javax.swing.GroupLayout(layered);
        layered.setLayout(layeredLayout);
        layeredLayout.setHorizontalGroup(
            layeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vMentreOrdena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layeredLayout.setVerticalGroup(
            layeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vMentreOrdena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layered.setLayer(vMentreOrdena, javax.swing.JLayeredPane.DEFAULT_LAYER);
    } 
    
    public void reset(){
        vMentreOrdena.setVisible(false);
        if(CtrlInterficie.seleccionaAllLlibres().size() > 10)   labAvis.setVisible(true);
        else labAvis.setVisible(false);
        panPregunta.setVisible(true);
        javax.swing.GroupLayout layeredLayout = new javax.swing.GroupLayout(layered);
        layered.setLayout(layeredLayout);
        layeredLayout.setHorizontalGroup(
            layeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layeredLayout.setVerticalGroup(
            layeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layered.setLayer(panPregunta, javax.swing.JLayeredPane.DEFAULT_LAYER);
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layered = new javax.swing.JLayeredPane();
        panPregunta = new javax.swing.JPanel();
        labAvis = new javax.swing.JLabel();
        bCancelar = new javax.swing.JButton();
        bHeur = new javax.swing.JButton();
        bBandB = new javax.swing.JButton();
        labInfo = new javax.swing.JLabel();

        labAvis.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        labAvis.setForeground(new java.awt.Color(255, 51, 51));
        labAvis.setText("<html>Compte! La quantitat de llibres és <b>molt gran per utilitzar un mètode exacte</b>. El temps d'espera de reordenació pot superar els 5 minuts.</html>");
        labAvis.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        bCancelar.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N
        bCancelar.setText("Cancel·lar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bHeur.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        bHeur.setText("Mètode heurístic");
        bHeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHeurActionPerformed(evt);
            }
        });

        bBandB.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        bBandB.setText("Mètode exacte");
        bBandB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBandBActionPerformed(evt);
            }
        });

        labInfo.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        labInfo.setText("Escull de quina forma vols ordenar:");

        javax.swing.GroupLayout panPreguntaLayout = new javax.swing.GroupLayout(panPregunta);
        panPregunta.setLayout(panPreguntaLayout);
        panPreguntaLayout.setHorizontalGroup(
            panPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPreguntaLayout.createSequentialGroup()
                .addGroup(panPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPreguntaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panPreguntaLayout.createSequentialGroup()
                                .addComponent(bBandB, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(bHeur, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panPreguntaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(labInfo))
                    .addGroup(panPreguntaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labAvis, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panPreguntaLayout.setVerticalGroup(
            panPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPreguntaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labAvis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(labInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(panPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBandB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHeur, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layeredLayout = new javax.swing.GroupLayout(layered);
        layered.setLayout(layeredLayout);
        layeredLayout.setHorizontalGroup(
            layeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layeredLayout.setVerticalGroup(
            layeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layered.setLayer(panPregunta, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(layered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bBandBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBandBActionPerformed
        cridaVistaMentreOrdena();
        vMentreOrdena.ordenar(false);
    }//GEN-LAST:event_bBandBActionPerformed

    private void bHeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHeurActionPerformed
        // TODO add your handling code here:
        cridaVistaMentreOrdena();
        vMentreOrdena.ordenar(true);
    }//GEN-LAST:event_bHeurActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        VistaPrincipal v = (VistaPrincipal)SwingUtilities.getWindowAncestor(this);
        v.ferVisiblePrincipal();
    }//GEN-LAST:event_bCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBandB;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bHeur;
    private javax.swing.JLabel labAvis;
    private javax.swing.JLabel labInfo;
    private javax.swing.JLayeredPane layered;
    private javax.swing.JPanel panPregunta;
    // End of variables declaration//GEN-END:variables
}
