/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package propLlibreria.Interficie;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author towerthousand
 */
public class VistaGestioModificarLlibre extends javax.swing.JPanel {

    /**
     * Creates new form VistaGestióAfegirEstanteria
     */
    public VistaGestioModificarLlibre() {
        initComponents();
    }

    public void resetFields() {
        ArrayList<ArrayList<String> > llibres = CtrlInterficie.seleccionaAllLlibres();
        String[] modelLlibres = new String[llibres.size()];
        for(int i = 0; i < llibres.size(); ++i) {
            String s = llibres.get(i).get(1) + ", de " + llibres.get(i).get(2) + ". ISBN:" + llibres.get(i).get(0);
            modelLlibres[i] = s;
        }
        comboLlibre.setModel(new javax.swing.DefaultComboBoxModel(modelLlibres));
        
        ArrayList<ArrayList<String> > tematiques = CtrlInterficie.seleccionaAllTematiques();
        String[] model = new String[tematiques.size()];
        javax.swing.DefaultListModel m = new javax.swing.DefaultListModel();
        for(int i = 0; i < tematiques.size(); ++i) {
            model[i] = tematiques.get(i).get(0);
            m.addElement(tematiques.get(i).get(0));
        }
        comboTematicaPrincipal.setModel(new javax.swing.DefaultComboBoxModel(model));
        listSecundaries.setModel(m);
        refill();
    }
    
    private void refill() {
        int selected = comboLlibre.getSelectedIndex();
        ArrayList<ArrayList<String> > llibres = CtrlInterficie.seleccionaAllLlibres();
        inputISBN.setText(llibres.get(selected).get(0));
        inputAutor.setText(llibres.get(selected).get(2));
        inputEditorial.setText(llibres.get(selected).get(3));
        inputTitol.setText(llibres.get(selected).get(1));
        spinAny.setValue(Integer.parseInt(llibres.get(selected).get(4)));
        spinEdicio.setValue(Integer.parseInt(llibres.get(selected).get(5)));
        comboTematicaPrincipal.setSelectedItem(llibres.get(selected).get(6));
        try {
            ArrayList<ArrayList<String> > l = CtrlInterficie.consultaTematiquesSLlibre(llibres.get(selected).get(1), llibres.get(selected).get(2), Integer.parseInt(llibres.get(selected).get(4)));
            setSelectedValues(listSecundaries, l);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error intern.\nCodi d'error: " + e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void setSelectedValues(JList list, ArrayList<ArrayList<String> > l) {
        list.clearSelection();
        for (int i = 0; i <  l.size(); ++i) {
            int index = getIndex(list.getModel(), l.get(i).get(0));
            if (index >= 0) {
                list.addSelectionInterval(index, index);
            }
        }
        list.ensureIndexIsVisible(list.getSelectedIndex());
    }

    public int getIndex(ListModel model, Object value) {
        if (value == null) return -1;
        if (model instanceof DefaultListModel) {
            return ((DefaultListModel) model).indexOf(value);
        }
        for (int i = 0; i < model.getSize(); i++) {
            if (value.equals(model.getElementAt(i))) return i;
        }
        return -1;
    }       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputAutor = new javax.swing.JTextField();
        labelAutor = new javax.swing.JLabel();
        inputTitol = new javax.swing.JTextField();
        labelTitol = new javax.swing.JLabel();
        labelEdicio = new javax.swing.JLabel();
        labelTematica = new javax.swing.JLabel();
        spinEdicio = new javax.swing.JSpinner();
        comboTematicaPrincipal = new javax.swing.JComboBox();
        labelAny = new javax.swing.JLabel();
        labelNom = new javax.swing.JLabel();
        inputISBN = new javax.swing.JTextField();
        labelEditorial = new javax.swing.JLabel();
        inputEditorial = new javax.swing.JTextField();
        spinAny = new javax.swing.JSpinner();
        botoModificar = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSecundaries = new javax.swing.JList();
        labelSecundaries = new javax.swing.JLabel();
        comboLlibre = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(212, 220, 245));
        setMaximumSize(new java.awt.Dimension(476, 405));
        setMinimumSize(new java.awt.Dimension(476, 405));
        setPreferredSize(new java.awt.Dimension(476, 405));

        jPanel1.setBackground(new java.awt.Color(212, 220, 245));

        labelAutor.setText("Autor");

        labelTitol.setText("Títol");

        labelEdicio.setText("Edició");

        labelTematica.setText("Temàtica");

        spinEdicio.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        spinEdicio.setMaximumSize(new java.awt.Dimension(10, 33));
        spinEdicio.setMinimumSize(new java.awt.Dimension(10, 33));
        spinEdicio.setPreferredSize(new java.awt.Dimension(10, 33));

        labelAny.setText("Any");

        labelNom.setText("ISBN");

        labelEditorial.setText("Editorial");

        spinAny.setModel(new javax.swing.SpinnerNumberModel(2000, 0, 2015, 1));
        spinAny.setMaximumSize(new java.awt.Dimension(10, 33));
        spinAny.setMinimumSize(new java.awt.Dimension(10, 33));
        spinAny.setPreferredSize(new java.awt.Dimension(10, 33));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTematica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboTematicaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelEdicio, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(labelAny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinAny, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinEdicio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTitol, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputEditorial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputAutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputTitol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNom)
                    .addComponent(inputISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitol)
                    .addComponent(inputTitol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAutor)
                    .addComponent(inputAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEditorial)
                    .addComponent(inputEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEdicio)
                    .addComponent(spinEdicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAny)
                    .addComponent(spinAny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTematica)
                    .addComponent(comboTematicaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        botoModificar.setText("Modificar");
        botoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoModificarActionPerformed(evt);
            }
        });

        listSecundaries.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listSecundaries);

        labelSecundaries.setText("Temàtiques secundàries");

        comboLlibre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboLlibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLlibreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboLlibre, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSecundaries, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboLlibre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSecundaries, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botoModificar)
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoModificarActionPerformed
        String autor = inputAutor.getText();
        String isbn = inputISBN.getText();                                          
        String editorial = inputEditorial.getText();                                     
        String titol = inputTitol.getText();                                            
        int any = (Integer) spinAny.getValue();                                         
        int edicio = (Integer) spinEdicio.getValue();          
        String tprincipal = (String) comboTematicaPrincipal.getModel().getSelectedItem();
        ListModel m = listSecundaries.getModel();
        ArrayList<String> sec = new ArrayList<String>();
        for(int i = 0; i < m.getSize(); ++i)
            if(listSecundaries.isSelectedIndex(i))
                sec.add((String)m.getElementAt(i));
        try {
            ArrayList<String> llibre = CtrlInterficie.seleccionaAllLlibres().get(comboLlibre.getSelectedIndex());
            int anyOrg = Integer.parseInt(llibre.get(4));
            String autorOrg = llibre.get(2);
            String titolOrg = llibre.get(1);
            CtrlInterficie.modificarEdicioLlibre(titolOrg, autorOrg, anyOrg, edicio);
            CtrlInterficie.modificarTPrincipalLlibre(titolOrg, autorOrg, anyOrg, tprincipal);
            CtrlInterficie.modificarIsbnLlibre(titolOrg, autorOrg, anyOrg, isbn);
            CtrlInterficie.modificarEditorialLlibre(titolOrg, autorOrg, anyOrg, editorial);
            CtrlInterficie.modificarTitolLlibre(titolOrg, autorOrg, anyOrg, titol);
            CtrlInterficie.modificarAutorLlibre(titol, autorOrg, anyOrg, autor);
            CtrlInterficie.modificarAnyLlibre(titol, autor, anyOrg, any);
             ArrayList<ArrayList<String> > l = CtrlInterficie.consultaTematiquesSLlibre(titol, autor, any);
            for(int i = 0; i < l.size(); ++i) CtrlInterficie.esborrarTSecundaria(titol, autor, any, l.get(i).get(0));
            for(int i = 0; i < sec.size(); ++i) CtrlInterficie.afegirTSecundaria(titol, autor, any, sec.get(i));
        }
        catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al modificar.\nCodi d'error: " + e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);  
                return;
        }
        JOptionPane.showMessageDialog(null, "Modificat correctament","Info",JOptionPane.INFORMATION_MESSAGE);            
        resetFields();
    }//GEN-LAST:event_botoModificarActionPerformed

    private void comboLlibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLlibreActionPerformed
        refill();
    }//GEN-LAST:event_comboLlibreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botoModificar;
    private javax.swing.JComboBox comboLlibre;
    private javax.swing.JComboBox comboTematicaPrincipal;
    private javax.swing.JTextField inputAutor;
    private javax.swing.JTextField inputEditorial;
    private javax.swing.JTextField inputISBN;
    private javax.swing.JTextField inputTitol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAny;
    private javax.swing.JLabel labelAutor;
    private javax.swing.JLabel labelEdicio;
    private javax.swing.JLabel labelEditorial;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelSecundaries;
    private javax.swing.JLabel labelTematica;
    private javax.swing.JLabel labelTitol;
    private javax.swing.JList listSecundaries;
    private javax.swing.JSpinner spinAny;
    private javax.swing.JSpinner spinEdicio;
    // End of variables declaration//GEN-END:variables
}
