/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package propLlibreria.Interficie;

/**
 *
 * @author Alice
 */
public class VistaPlantilla extends javax.swing.JPanel {

    /**
     * Creates new form VistaPlantilla
     */
    public VistaPlantilla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pContingut = new javax.swing.JPanel();
        pNavegabilitat = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        pContingut.setBackground(new java.awt.Color(204, 204, 255));
        pContingut.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N

        pNavegabilitat.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Navegabilitat");

        javax.swing.GroupLayout pNavegabilitatLayout = new javax.swing.GroupLayout(pNavegabilitat);
        pNavegabilitat.setLayout(pNavegabilitatLayout);
        pNavegabilitatLayout.setHorizontalGroup(
            pNavegabilitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNavegabilitatLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel2)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        pNavegabilitatLayout.setVerticalGroup(
            pNavegabilitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pNavegabilitatLayout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        pHeader.setBackground(new java.awt.Color(255, 255, 255));
        pHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pHeader.setFocusable(false);

        jLabel1.setText("Coses de la capcelera");

        javax.swing.GroupLayout pHeaderLayout = new javax.swing.GroupLayout(pHeader);
        pHeader.setLayout(pHeaderLayout);
        pHeaderLayout.setHorizontalGroup(
            pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHeaderLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel1)
                .addContainerGap(221, Short.MAX_VALUE))
        );
        pHeaderLayout.setVerticalGroup(
            pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pHeaderLayout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout pContingutLayout = new javax.swing.GroupLayout(pContingut);
        pContingut.setLayout(pContingutLayout);
        pContingutLayout.setHorizontalGroup(
            pContingutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pNavegabilitat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pContingutLayout.setVerticalGroup(
            pContingutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pContingutLayout.createSequentialGroup()
                .addComponent(pHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                .addComponent(pNavegabilitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pNavegabilitat.getAccessibleContext().setAccessibleName("pNavegabilitat");
        pHeader.getAccessibleContext().setAccessibleName("pHeader");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pContingut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pContingut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pContingut.getAccessibleContext().setAccessibleName("PContingut");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pContingut;
    private javax.swing.JPanel pHeader;
    private javax.swing.JPanel pNavegabilitat;
    // End of variables declaration//GEN-END:variables
}
